# Generated by Django 5.2.7 on 2025-10-04 15:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_name",
                    models.CharField(max_length=200, verbose_name="Item Name"),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Describe the condition, highlights, missing pages, etc.",
                        verbose_name="Description",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Price ($)"
                    ),
                ),
                (
                    "seller_name",
                    models.CharField(max_length=100, verbose_name="Your Name"),
                ),
                (
                    "contact_info",
                    models.CharField(
                        help_text="WhatsApp number or email",
                        max_length=200,
                        verbose_name="Contact Info",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="item_images/",
                        verbose_name="Photo of Item",
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[("book", "Textbook"), ("notes", "Study Notes")],
                        default="book",
                        max_length=10,
                        verbose_name="Type",
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Author/Creator",
                    ),
                ),
                (
                    "course",
                    models.CharField(
                        blank=True,
                        help_text="e.g., MATH 101, CS 201",
                        max_length=50,
                        null=True,
                        verbose_name="Course Code",
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("excellent", "Excellent - Like New"),
                            ("good", "Good - Minor Wear"),
                            ("fair", "Fair - Some Wear"),
                            ("poor", "Poor - Heavy Wear"),
                        ],
                        default="good",
                        max_length=20,
                        verbose_name="Condition",
                    ),
                ),
                (
                    "date_posted",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Date Posted"
                    ),
                ),
                ("is_sold", models.BooleanField(default=False, verbose_name="Sold")),
                (
                    "view_count",
                    models.PositiveIntegerField(default=0, verbose_name="Views"),
                ),
            ],
            options={
                "verbose_name": "Item",
                "verbose_name_plural": "Items",
                "ordering": ["-date_posted"],
            },
        ),
    ]
